---
- name: set localtime to Asia/Tehran
  command: cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime

- name: Change timezone in php.ini
  lineinfile:
    dest: "/etc/php5/apache2/php.ini"
    line: "date.timezone = Asia/Tehran"
  notify:
    - restart httpd

- name: Install necessary packages
  apt:
    name: python-pip
    state: present
    update_cache: yes

- name: Install python packages
  command: pip install {{ item }}
  with_items:
    - "suds"
    - "suds_requests"

- name: Create a folder for external scripts
  file:
    path: "/usr/lib/zabbix/externalscripts"
    state: "directory"
    mode: "0755"

- name: Copy scripts to zabbix externalscripts directory
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/zabbix/externalscripts/{{ item }}"
    mode: "0755"
  with_items:
    - "get_delta_of_last1h_registered_requests.sh"
    - "get_delta_of_last1h_sim_card_count.sh"
    - "get_delta_of_last24h_registered_requests.sh"
    - "get_delta_of_last24h_sim_card_count.sh"
    - "get_delta_of_last1h_minus_1_and_2.sh"
    - "get_delta_of_last1h_minus_1_and_plus_1.sh"
    - "get_item_hourly_count.sh"
    - "get_item_daily_count.sh"
    - "get_mnp_web_service_call_count.sh"
    - "get_reported_requests_from_db.sh"
    - "get_reported_requests_from_ftp.sh"

- name: Copy other helper scripts to externalscripts
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/zabbix/externalscripts/{{ item }}"
    mode: "0755"
  with_items:
    - "init_ftp_header.sh"

- name: Copy Action scripts to alert directory
  template:
    src: "{{ item }}.j2"
    dest: "/usr/lib/zabbix/alertscripts/{{ item }}"
    mode: "0755"
  with_items:
    - "sendSMS.py"
  
- name: Create lib subdir in zabbix externalscripts directory
  file:
    path: "/usr/lib/zabbix/externalscripts/lib"
    state: "directory"
    mode: "0755"

- name: Copy additional scripts to lib directory
  copy:
    src: "{{ item }}"
    dest: "/usr/lib/zabbix/externalscripts/lib"
    mode: "755"
  with_items:
    - "greg2jalali.sh"
    - "examineMNPFile-0.0.1-SNAPSHOT-jar-with-dependencies.jar"

- name: Create zabbix-cli directory
  file: 
    path: "/opt/zabbix-cli"
    state: "directory"
    mode: "0755"

- name: Git clone zabbix cli
  git:
    repo: "https://github.com/usit-gd/zabbix-cli.git"
    dest: "/opt/zabbix-cli" 

- name: Install zabbix cli
  command: "/opt/zabbix-cli/setup.py install"
  args:
    chdir: "/opt/zabbix-cli"

- name: Intialize zabblix cli
  command: "/usr/local/bin/zabbix-cli-init -z http://localhost/zabbix"

- name: Copy zabbix-cli_auth file to root home
  template:
    src: "zabbix-cli_auth.j2"
    dest: "/root/.zabbix-cli_auth"
    mode: "0400"

- name: Copy zabbix portability monitoring templates to /tmp
  copy:
    src: "{{ item }}"
    dest: "/tmp/{{ item }}"
  with_items:
    - "zbx_export_templates.xml"
    - "zbx_export_hosts.xml"

- name: Import zabbix portability monitoring template
  shell: 'printf "/tmp/{{ item }}\n0\n" | /usr/local/bin/zabbix-cli --command import_configuration'
  with_items:
    - "zbx_export_templates.xml"
    - "zbx_export_hosts.xml"

- name: Create MNP Monitors group
  shell: 'printf "MNP Monitors\n\n\n" | /usr/local/bin/zabbix-cli --command create_usergroup'

- name: Add permissions to group
  shell: 'printf "MNP Monitors\nPortability Monitoring Hosts\nRO\n" | /usr/local/bin/zabbix-cli --command add_usergroup_permissions'
