---
- hosts: Monitoring
  become: true
  become_user: root

  vars:

    mysql:
      schema: "mnp"
      user: "zab_mon"
      password: "ZAaBbMMMon90618"
      host: "Portal-DB1"
    zabbix:
      admin_username: "Admin"
      admin_password: "Adm11npa55$$"

  tasks:
    - name: set localtime to Asia/Tehran
      command: cp /usr/share/zoneinfo/Asia/Tehran /etc/localtime

    - name: Change timezone in php.ini
      lineinfile:
        dest: "/etc/php5/apache2/php.ini"
        line: "date.timezone = Asia/Tehran"
      notify:
        - restart httpd

    - name: Create a folder for external scripts
      file:
        path: "/usr/lib/zabbix/externalscripts"
        state: "directory"
        mode: "0755"

    - name: Copy scripts to /etc/zabbix/external/scripts
      template:
        src: "{{ item }}.j2"
        dest: "/usr/lib/zabbix/externalscripts/{{ item }}"
        mode: "0755"
      with_items:
        - "get_sms_sent_count.sh"
        - "get_otp_verified_count.sh"
        - "get_delta_of_minus_1_and_2_status.sh"
        - "get_sim_card_hourly_count.sh"
        - "get_sim_card_daily_count.sh"
        - "get_delta_of_last1h_sim_card_count.sh"
        - "get_delta_of_last24h_sim_card_count.sh"
      
    - name: Create zabbix-cli directory
      file: 
        path: "/opt/zabbix-cli"
        state: "directory"
        mode: "0755"

    - name: Git clone zabbix cli
      git:
        repo: "https://github.com/usit-gd/zabbix-cli.git"
        dest: "/opt/zabbix-cli" 

    - name: Install zabbix cli
      command: "/opt/zabbix-cli/setup.py install"
      args:
        chdir: "/opt/zabbix-cli"

    - name: Intialize zabblix cli
      command: "/usr/local/bin/zabbix-cli-init -z http://localhost/zabbix"

    - name: Copy zabbix-cli_auth file to root home
      template:
        src: "zabbix-cli_auth.j2"
        dest: "/root/.zabbix-cli_auth"
        mode: "0400"

    - name: Copy zabbix portability monitoring template to /tmp
      copy:
        src: "zbx_export_templates.xml"
        dest: "/tmp/zbx_export_templates.xml"

    - name: Import zabbix portability monitoring template
      shell: 'printf "/tmp/zbx_export_templates.xml\n0\n" | /usr/local/bin/zabbix-cli --command import_configuration'
     
  handlers:
    - name: restart httpd
      service:
        name: apache2
        state: restarted

- hosts: Portal-DB1
  become: true
  become_user: root

  vars:
    mysql:
      schema: "mnp"
      user: "zab_mon"
      password: "ZAaBbMMMon90618"
      host: "localhost"
    zabbix:
      monitoring_ip_address: "Monitoring"

  tasks:
    - name: Create monitoring user
      shell: echo "CREATE USER {{ mysql.user }}@{{ zabbix.monitoring_ip_address }} IDENTIFIED BY '{{ mysql.password }}';" | mysql -u root
      ignore_errors: yes

    - name: Grant SELECT privilges to user
      shell: echo "GRANT SELECT ON lportal.{{ item }} TO {{ mysql.user }}@{{ zabbix.monitoring_ip_address }};" | mysql -u root
      with_items:
        - mnp_requestinfolog

    - name: Flush privileges
      shell: echo "FLUSH PRIVILEGES" | mysql -u root
