---
- hosts: zabbix
  become: true
  become_user: root

  vars:

    zabbix:
      admin_username: "Admin"
      admin_password: "zabbix"
    ftp:
      server_address: "172.20.20.1"
      username: "user1"
      password: "xxxx" 
    sms:
      username: "username"
      password: "xxxx"
      wsdl_url: "http://esb.rightel.ir/RightelSendSMS?wsdl"
      originator: "12345"

  roles:
    - mnp_monitoring_zabbix

- hosts: Portal-DB1
  become: true
  become_user: root

  vars:
    mysql:
      schema: "mnp"
      user: "username"
      password: "xxxx"
      host: "localhost"
    zabbix:
      monitoring_ip_address: "10.10.10.22"

  roles:
    - mnp_monitoring_db
